// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjxidnohxtcupgyswjfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqeGlkbm9oeHRjdXBneXN3amZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTYxMDIsImV4cCI6MjA3MTkzMjEwMn0.HWUYqNkKlh7-VCvjcDOeUv_om-Tw_ZzSk6yBqNS1ZEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});